# Generated by Django 2.2.5 on 2019-11-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
