# Generated by Django 2.2.5 on 2019-11-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='delete_flag',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='部員ID'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='member_name',
            field=models.CharField(max_length=100, verbose_name='部員名'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.CreateModel(
            name='EnqueteModel',
            fields=[
                ('enquete_id', models.AutoField(primary_key=True, serialize=False, verbose_name='アンケートID')),
                ('enquete_name', models.CharField(max_length=200, verbose_name='アンケート名')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='登録日')),
                ('answer_date', models.DateField(null=True, verbose_name='回答日')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.MemberModel')),
            ],
        ),
    ]
