# Generated by Django 2.2.3 on 2019-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnqueteModel',
            fields=[
                ('enquete_id', models.AutoField(primary_key=True, serialize=False)),
                ('enquete_name', models.CharField(max_length=200)),
            ],
        ),
    ]
