# Generated by Django 2.2.3 on 2019-07-15 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='enquetemodel',
            name='member_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashborad.MemberModel'),
            preserve_default=False,
        ),
    ]
