# Generated by Django 2.2.3 on 2019-07-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0004_auto_20190715_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtypemodel',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemtypemodel',
            name='item_type_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtypemodel',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('item_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashborad.ItemTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_content', models.CharField(max_length=200)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('enquete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashborad.EnqueteModel')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashborad.ItemModel')),
            ],
        ),
    ]
