# Generated by Django 2.2.3 on 2019-07-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0005_auto_20190716_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='member_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashborad.MemberModel'),
            preserve_default=False,
        ),
    ]
